### ISSUE TITLE
Difficulty with chalkdust wraith on day 1

### ISSUE THREAD

**Issue by magus-prime** [soolar/sl_ascend#1]
I've used cc_ascend for some time but thought I'd try your fork today for my second HC Std ascension of 2019.  When in the Haunted Billiard Room the script, consistently, gave up when fighting chalkdust wraiths.

The CCS used by the script appeared to favor physical damage attacks against the monster and that's ineffective against ghosts.  After the script gave up I continued the combat in the relay browser and easily finished the encounter in one round.

The character in question has all skills except the Dreadsylvania castle skills, and all in standard shinies.  This run is a HC TT run.

Thank you for attempting to continue updating cc_ascend.

**Comment by soolar** [comment]
Yeah, I'm encountering that too as a Disco Bandit. Will look in to that today!

**Comment by faceboogle** [comment]
Hello

I had this too a couple of days ago. I'm not sure what the commit (7804219?) did but the script didn''t seem to find / use a source of elemental damage in my HC DG run

Thanks
E
