### ISSUE TITLE
Please equip ranged weapon on Dark Gyffte (since Sinister Charm is almost always turned on)

### ISSUE THREAD

**Issue by medchem** [soolar/sl_ascend#102]
The script repeatedly equip oversized pizza cutter on my lv 11 character, causing frequent torpor visit. Since sinister charm is almost always turned on (when possible), it maybe more adequate to play as mox class, and set ranged weapon (or piercing gaze when not in mist form) as default attack option.

**Comment by MatthewDarling** [comment]
Within Dark Gyfte, is there a list of easily acquired 1-handed ranged weapons? Lead Yo-Yo from Armorer & Leggerer works once you have 25 base moxie, just wondering about  what to use before that + possible upgrades.

Could use 2-handed weapons if Latte & Kramco aren't available, as well. Stolen Accordion to start, maybe grab an upgrade from Armorer & Leggerer later.

**Comment by medchem** [comment]
Just personal opinion: start with stolen accordion or disco ball, and get bone flute or infernal fife on lv6-lv7, laser cannon in lv10, and Saturday night special in lv 11.   If needing to use latte or kramco things gets more complicated though.
Ideally in DG weapon can be used rarely. If starting with enough HP, just one-shot with piercing gaze and regen with sanguine magnetism. But since sl_ascend seems to use attack - feast - chill combat macro a lot, weapon power should still be considered, in that situation ranged is better (unless we put prenatural strength into higher priority, which I tried today and worked).

**Comment by jaspercb** [comment]
Off-hand IOTMs are really, really good. I want to push back on using 2h ranged equipment.

Although this would be mitigated in high-skill runs by using the correct combat skill when in a form.

**Comment by medchem** [comment]
Or maybe just make Preternatural Strength a higher priority, so that melee weapon do make acceptable damage. 
Tried this modification in bat_pickSkills (in my own machine) and seems to be doable (and please see attachment)
[sl_batpath.ash.txt](https://github.com/soolar/sl_ascend/files/2994578/sl_batpath.ash.txt)
:
`
foreach sk in $skills[
        Chill of the Tomb,				
	Sinister Charm,
        Madness of Untold Aeons,
        Preternatural Strength,
        Hypnotic Eyes,
        Piercing Gaze,
        Blood Chains,		
        Piercing Gaze,
        Ceaseless Snarl,
	Blood Cloak,
        Sanguine Magnetism,
        Mist Form,  
	Ensorcel,
`

**Comment by xande-1** [comment]
Disco ball is 1-handed, and trivial to obtain.  With outstattting enemies, the base damage of the weapon doesn't matter; I've done entire runs with a disco ball.

There's no reason to ever buy Preternatural Strength except for the tower test.  Moxie will handle all combat needs, and raising strength just increases HP of scaling monsters.  Those hp could be better spent on something that speeds up the run.

**Comment by jaspercb** [comment]
A recent commit added use for the disco ball when in a non-mist form, which should mitigate the "plonk plonk attack you with my 5 damage spellcasting weapon" when in alternate forms. Assuming that's what this was stemming from.

**Comment by medchem** [comment]
Thanks. Will test it tomorrow, if working maybe close this issue.

**Comment by medchem** [comment]
With recently improved HP management, DGs got less beaten up and less relying on feast, so weapon  attack is less a issue. Though still not seeing disco ball used (the script rarely use form), but still mark as closed.
