### ISSUE TITLE
Flock of bats form not used in the Defiled Alcove

### ISSUE THREAD

**Issue by faceboogle** [soolar/sl_ascend#106]
Hello

The script has just completed the Cyrpt quest, and it used the flock of bats form in the Nook but didn't used it in the Alcove. It would be better to use that form in the Alcove as higher initiative increases chance of finding modern zmobies
[http://kol.coldfront.net/thekolwiki/index.php/The_Defiled_Alcove](url)

Cheers
E

**Comment by jaspercb** [comment]
I didn't add that since you also want to be running -combat, but you are probably right that (assuming you can survive it) the added +initiative is worth dropping 15% NC.

**Comment by faceboogle** [comment]
> I didn't add that since you also want to be running -combat, but you are probably right that (assuming you can survive it) the added +initiative is worth dropping 15% NC.

According to the wiki the modern zobmie is a combat adventure, so I'm not sure that -combat is needed here. Thanks for explaining the reason though

**Comment by jaspercb** [comment]
Nah, I'll get around to fixing this eventually. :)
