### ISSUE TITLE
Select the right votes in Dark Gyffe

### ISSUE THREAD

**Issue by txrangersxx** [soolar/sl_ascend#108]
On voting options do not select anything with familiars and always select the +HP item

**Comment by MatthewDarling** [comment]
The HP buff from Voting Booth is a percentage boost, and I thought those didn't work in Dark Gyfte. Is the Voting Booth special and actually does work?

**Comment by jaspercb** [comment]
Nope, the +HP modifier doesn't work.

Also, we import https://github.com/Ezandora/Voting-Booth for this.

**Comment by taltamir** [comment]
Well, that project is also open source so code could be submitted there too and ezandora could accept it.

**Comment by Saklad5** [comment]
I opened an [issue](https://github.com/Ezandora/Voting-Booth/issues/2) for this. It may just be better to simply fork it for sl_ascend, though: this is a fairly simple thing to automate, and sl_ascend should be prioritizing initiatives based on the current circumstances. Making her script do that would necessitate a complete overhaul anyway.

**Comment by jaspercb** [comment]
This was fixed upstream: https://github.com/Ezandora/Voting-Booth/commit/55dc7a30a3fbdf0c4d533bd460ed6a56a871fac6, this can be closed
