### ISSUE TITLE
Issues with Hedge Maze in Dark Gyffe

### ISSUE THREAD

**Issue by txrangersxx** [soolar/sl_ascend#109]
When the script does the hard side of the hedge maze in Dark Gyffe it does not heal after each step and fails

**Comment by soolar** [comment]
I know this is a bit of an old issue, but can you provide some logs just for the bit where it fails? If not, I'll have a look at fixing it next time I run in to it. It's low priority since you can just manually torpor and then rerun, but it's still worth fixing.

**Comment by txrangersxx** [comment]
I haven't done DG runs for a few weeks but If I remember right this started workedin the last few I did so Im closing
