### ISSUE TITLE
Tried to adventure in the Hole in the Sky when not open

### ISSUE THREAD

**Issue by magus-prime** [soolar/sl_ascend#11]
The script tried to complete the Shen half of the Talisman quest and got the section of the quest that requires adventuring in the Hole in the Sky.  The area hadn't been opened.  

The script then went back and opened the zone.

Perhaps consider opening that zone while finishing the castle?  We'll have to go there, at least in HC, at some point and with -combat, and a mohawk wig, it normally takes a only a few turns.

**Comment by soolar** [comment]
Did the script actually abort as an error when it tried to go to the hole in the sky, or did it just realize it couldn't and go unlock it? If it's the latter I don't think this is really an issue.

**Comment by magus-prime** [comment]
It didn't abort it just complained about it with a red error message and then proceeded to open the zone.  I submitted the issue as more of a suggestion on, perhaps, moving the opening of the zone logic.

**Comment by soolar** [comment]
Eh, I don't really see any particular benefit to unlock the hole in the sky before you need it, personally.
