### ISSUE TITLE
new code for scheduled zepplin noncombat not working

### ISSUE THREAD

**Issue by taltamir** [soolar/sl_ascend#115]
```
Uh oh, we expected to get a scheduled Zeppelin noncombat there but didn't. That's not supposed to happen. There's a bug in Jeparo's new code!
```

received this error 5 times already today (2019-03-23. I just ran the script again after every time).

**Comment by taltamir** [comment]
Also, putting aside the scheduled noncom. Isn't it possible to get non-scheduled noncoms as well via -combat or just random chance?

**Comment by jaspercb** [comment]
Agreed that clover use here is fantastic - working on that. Logs from this case would be great, still.

**Comment by taltamir** [comment]
This seems to have been fixed. I have seen a recent update that mentioned something about changing the logic there, and this ran it successfully got through the zepplin with no errors.
