### ISSUE TITLE
Consider running with less ML

### ISSUE THREAD

**Issue by magus-prime** [soolar/sl_ascend#12]
At the end of Day two my HC TT was already level 12 and was 90% of the way to level 13.  The script was running with +79 ML for most of the day and that might have contributed to the overall lack of meat on the first two days.

**Comment by soolar** [comment]
I definitely do want to make the script stop running ML once you're level 13, but I dunno if it's a good idea before that. I'm pretty sure the script does slowly strip away ML (at least from the MCD) when you get beaten up, but... yeah. Hmm, I'll think about it.
