### ISSUE TITLE
lobsterfrogman + I voted sticker trick

### ISSUE THREAD

**Issue by taltamir** [soolar/sl_ascend#125]
there is apparently a trick with the "I voted sticker" (from the voting both IOTM) synergizing with meteor lore.
http://kol.coldfront.net/thekolwiki/index.php/%22I_Voted!%22_sticker

The sticker will let you fight a monster every 11 turns. this is predictable and tracked by mafia. the first free fights are free fights, the rest are normal fights. I am not sure if using this on the free fights wastes a free fight or not (will try to test and post here later on).

Anyways, the trick is to equip the i voted sticker when the time is right, and go to sonofa beach, this will immediately force a fight with one of the monsters i voted sticker can spawn. then use macrometeorite to switch it to a lobsterfrogman and kill it. This is much cheaper than other lobsterfrogman acquisition methods

**Comment by taltamir** [comment]
```
_voteFreeFights
```
this variable starts at 0 every day, it counts how many free fights were used by vote. it maxes out at 3. If free fights are wasted by this trick then it should only be called when this variable equals 3. If not then it can be ignored.

```
lastVoteMonsterTurn
```
I think this tells you what was the last turn (in turns played total across all ascensions) where the last vote monster was encountered... not 100% sure though. will have to test it.

**Comment by jaspercb** [comment]
I upped the priority in https://github.com/soolar/sl_ascend/commit/fe881c979bac5e3ca1f43bc7a5a34a7b968a26dd . I think we currently don't use it for the very last lobsterfrogman because there might be a copy floating around, which seems stupid to me so I'm changing it.

**Comment by taltamir** [comment]
thanks. also, I got around to testing it, and it does waste a free fight if you use this trick before having used the 3 free fights.

Mafia/guide incidentally seem to be tracking those free fights incorrectly. They count vote free fights on beating the fight not on encountering it.

**Comment by Saklad5** [comment]
Is there a reason that this issue is still open?

**Comment by taltamir** [comment]
does sl_ascend make sure to wait until the 3 free fights have been used up before using this trick? (to do otherwise will be wasting the free fights).
If yes then this can be closed. If no, then probably need to adjust it to first use the free fights normally and then use the lobsterfrogman trick

**Comment by MatthewDarling** [comment]
It doesn't enforce that, no. But free fights are used to burn delay, and burning delay is higher priority than the war quest. So it would only ever put a free vote fight in Sonofa Beach if there's nowhere to burn delay.

Does that seem sufficient? If not, where should free vote fights go at level 12+ without any delay zones?

**Comment by taltamir** [comment]
If there are not any specific delay burn zones to do, then you can do the free fight anywhere really. Well, some free fights can be used to advance neverending party quests.
But if you really have nowhere special to burn it then the free fight is being done for the XP and loot. And it is still more optimal to use it as is rather than converting a free fight into an adventure burning fight in sonofa.... unless for some reason trying to preserve those means you don't manage to get all 5 sonofa encounters which is a risk that probably means this is not worth altering. So I think we can close this one?

**Comment by jaspercb** [comment]
I agree that getting one free fight is not worth risking delaying sonofa beach. I agree this should probably be closed.
