### ISSUE TITLE
Getting fat loot tokens from Daily Dungeon instead of FantasyRealm

### ISSUE THREAD

**Issue by faceboogle** [soolar/sl_ascend#132]
Current run is HC DG. Script is heading to the DD for a token - this is day one but it seemed to do the same all during my previous run which lasted six days. Doesn't seem to want to go to FantasyRealm.

**Comment by jaspercb** [comment]
Does Mafia know you have FantasyRealm? Check
`prefref frAlways'
If it's false, set it to true with
`set frAlways=true`

**Comment by faceboogle** [comment]
Okay, mafia didn't know I have FantasyRealm - sorry
