### ISSUE TITLE
Was informed to report fighting a crate

### ISSUE THREAD

**Issue by michaeljhopkins** [soolar/sl_ascend#134]
The config file says to report if I fight a crate. Unsure what to attach however. Step to.....reproduce what I did, no guarantee this will reproduce bug

1. Svn installed script for first time into mafia
1. Ran the gcli command to initiate it
1. Script ran successfully for ~120 turns
1. Manually stopped to look into config file/page in relay browser
1. Adjusted many options (too many to manually type. Happy to screen shot or whatever)
1. Started script again
1. Ended up in noob cave

Note, please close or delete this issue if it is not helpful, only reporting because script told me to

======EDIT===========EDIT=============EDIT===============

As it turns out I did not save the config file. So updated steps below

1. Svn installed script for first time into mafia
1. Ran the gcli command to initiate it
1. Script ran successfully for ~120 turns
1. Manually stopped to look into config file/page in relay browser
1. Adjusted many options (did not save file however)
1. Started script again
1. Ended up in noob cave

**Comment by jaspercb** [comment]
When you manually stopped the script, did you do using the KoLmafia "stop the world" interface, or with sl_interrupt via the soolascend relay interface? That can be a source of this stuff, since some internal state may not get set.

Also the adventures around the noob cave excursion would be great to know. Maybe upload the surrounding 10 adventures to Pastebin and annotate the part where you stopped the script?

**Comment by michaeljhopkins** [comment]
It's hard to recall exactly, I BELIEVE i stopped this script after the manual choice for the gob lobster fight `ln 691`. One of the crate attacks (I don't remember which) was a manual click on the cave. Using the forced override in the options did resolve the issue

Again, I want to reiterate, this is not a complaint, nor something I'm upset happened. Only posting because I was informed to

https://pastebin.com/LpgJtzQ2

**Comment by jaspercb** [comment]
Yeah I don't really know what's going on here, sorry. It's clearly God Lobster related, which makes sense (I think we engage the combat script by manually navigating the God Lobster noncombat and then calling ccAdv), but... yeah. I dunno.

**Comment by michaeljhopkins** [comment]
Close this issue then. If you're good, I'm good.
