### ISSUE TITLE
Doesn't Recognize latest KoLmafia build

### ISSUE THREAD

**Issue by ClubbyMcClubberson** [soolar/sl_ascend#135]
I'm getting this error, and I'd rather not roll back to the previous build of KoLmafia just to get it to work:

'sl_ascend.ash' requires revision r19109 of kolmafia or higher (current: r19010). Up-to-date builds can be found at https://ci.kolmafia.us/.

**Comment by jaspercb** [comment]
Looks to me like r19010 is waaay before r19109. Like, over a hundred versions before (XX010 vs XX109). Try downloading and using https://ci.kolmafia.us/job/Kolmafia/lastSuccessfulBuild/artifact/dist/KoLmafia-19145.jar, from the page linked there.

**Comment by ClubbyMcClubberson** [comment]
Yeah...apparently I can't read lol.  
Thanks for writing/maintaining the script!  I'll update my software.
