### ISSUE TITLE
[vampyre] Don't fight swarm of ghoul whelps in Dark Gyffte

### ISSUE THREAD

**Issue by medchem** [soolar/sl_ascend#139]
![Screen Shot 04-01-19 at 03 02 PM](https://user-images.githubusercontent.com/623313/55309131-6e5a9f00-548f-11e9-884e-9e951f74954c.PNG)
[ast154251_20190401.txt](https://github.com/soolar/sl_ascend/files/3028096/ast154251_20190401.txt)

(Please see line 4052-4091 in the log)
Since choosing to fight the ghoul whelps in the NC means less chance of dieting pill, which is often important in DG. Optimally skip it (and turn Bat form on) when doing the cranny.

**Comment by txrangersxx** [comment]
Is it worth it to slow down the the Crypt to get diet pills?

**Comment by medchem** [comment]
@txrangersxx 
This depends on IoTM owned. For players doing 5-day hardcore run, if not owning doctor's bag and vampyre cloak, getting 8 dieting pills in day 2 means filling 6-8 extra stomach space, which can be 84-184 extra adventures, therefore worth slowing down the Crypt. 
If the player have extra blood bag from IoTM it maybe not worth it, though.

**Comment by Saklad5** [comment]
I’d argue it isn’t worth trading a guaranteed progress boost for a very slightly increased chance at a powerful spleen item.

**Comment by jaspercb** [comment]
I'd approve of logic like "if we have access to the +item passive and bats form, banish the one that doesn't drop dieting pills, then run bats form until we have some number of dieting pills (4 for SC, 6 for HC? or make it configurable)", then run +ml and -com to completion.

**Comment by faceboogle** [comment]
My ninth HC DG run was done nearly all by script and it ended up as 5/786. I certainly feel it could have reduced day count by getting dieting pills (i.e. boosting item% and sniffing / banishing for more gaunt ghouls) instead of doing the NC

**Comment by MatthewDarling** [comment]
[We have banishes for Gluttonous Ghuol now](https://github.com/soolar/sl_ascend/blob/master/BUILD/monsters/banish.dat#L17), so that's one step taken care of.

I think it's safe to run +ml and -combat the entire time, as long as we skip the noncombat, right? So conditionally tweaking the choice adventure preference would take care of that.
