### ISSUE TITLE
[vampyre] Please visit the trappers after defeating Sharona in Darke Gyffte

### ISSUE THREAD

**Issue by medchem** [soolar/sl_ascend#141]
[ast154251_20190402.txt](https://github.com/soolar/sl_ascend/files/3032505/ast154251_20190402.txt)
See line 1940-2030 in the log. 
After Sharona defeat the script repeatedly visit the Peak hoping to fight groar. Should end the quest.

**Comment by txrangersxx** [comment]
This has been fixed in a updated version of the script.  Be sure to do an SVN Update

**Comment by txrangersxx** [comment]
If not this is a duplicate of 104

**Comment by medchem** [comment]
Will test it next run. Thanks

**Comment by medchem** [comment]
Confirm bug fixed. Issue closed.
