### ISSUE TITLE
Trying to use Vampyre Skills in HCStd

### ISSUE THREAD

**Issue by txrangersxx** [soolar/sl_ascend#143]
Script is trying to use baneful howl in the Pyramid and Gremlins in HCStd

**Comment by soolar** [comment]
The next time you encounter this, can you go to the gCLI and enter `ash have_skill($skill[Baleful Howl])` and tell me what it returns? I have a feeling this is a mafia bug, not an sl_ascend bug.

**Comment by taltamir** [comment]
I just got this issue in softcore standard. I used ash have_skill($skill[Baleful Howl]) and it returned true.

**Comment by txrangersxx** [comment]
i think this is were it is occuring and I don't think it is a mafia bug

use 1 &quot;2 Love Me, Vol. 2&quot;

Visiting Relaxing Hot Tub in clan VIP lounge
You lose an effect: Beaten Up (0)
You gain 1,723 hit points
Took choice 1342/2: unknown
choice.php?whichchoice=1342&option=2&pwd&sk[]=12&sk[]=13&sk[]=14&sk[]=15&sk[]=16&sk[]=17&sk[]=18&sk[]=21&sk[]=22&sk[]=23&sk[]=24&sk[]=25&sk[]=26&sk[]=27&sk[]=28&sk[]=31&sk[]=32&sk[]=34&sk[]=35&sk[]=36&sk[]=37&sk[]=38
You have learned Baleful Howl
You have learned Ceaseless Snarl
You have learned Wolf Form
You have learned Preternatural Strength
You have learned Flesh Scent
You have learned Ferocity
You have learned Intimidating Aura
You have learned Blood Chains
You have learned Chill of the Tomb
You have learned Blood Cloak
You have learned Mist Form
You have learned Madness of Untold Aeons
You have learned Hypnotic Eyes
You have learned Macabre Cunning
You have learned Sanguine Magnetism
You have learned Perceive Soul
You have learned Ensorcel
You have learned Flock of Bats Form
You have learned Sinister Charm
You have learned Batlike Reflexes
You have learned Sharp Eyes
You have learned Spot Weakness
Took choice 1342/1: unknown
choice.php?whichchoice=1342&option=1&pwd

**Comment by taltamir** [comment]
it says a bunch of unknown choices, do you know what those were? Also, it might actually be a bug in kol.

Here is a similar bug where I thought it was a mafia bug, but was informed it is a kol bug. Although there is precedence for mafia catching and correcting for that
https://kolmafia.us/showthread.php?23649-Mafia-thinks-that-Gingerbread-mob-hit-is-still-available-in-standard-even-when-not&p=151870&viewfull=1#post151870

**Comment by txrangersxx** [comment]
i have no idea what they do but I am going to hypothesize that the script tried to heal in Torpor after getting beatup by the 2 love vol 2

**Comment by jaspercb** [comment]
Yeah. I think that's what's happening, Mafia adjusts skills on the outgoing POST, and that method isn't guarded by an "am I a vampyre" check. Thanks!

**Comment by taltamir** [comment]
So it is a mafia issue then, right?

**Comment by jaspercb** [comment]
Yes, sort of, but also it's fixable on our end. I'll fix it tomorrow.
