### ISSUE TITLE
Inappropriate sausage consumption

### ISSUE THREAD

**Issue by magus-prime** [soolar/sl_ascend#15]
At the beginning of Day Three the script proceeded to make and consume nine magical sausages.  It then made and consumed a sausage whenever it could throughout the rest of the day.

The character had a max MP of less than 500 when the nine sausages were consumed.  That wasted a lot of potential MP restoratives that were needed later in the day.

There seems to be a check that's either incomplete or failing as this flashed by in the gCLI:
"We're gonna slurp up some sausage, let's make sure we have enough max mp"

**Comment by soolar** [comment]
It maximizes your mp, but currently doesn't save them for later if your best max mp is under 999. I guess I could add that, but then it might not eat any sausage on day one in non-myst classes? I'm not sure if that would be better...

**Comment by jaspercb** [comment]
I think we can compromise between these options with a rule like "Don't consume sausages, unless needed for MP restoration, if we have fewer than X sausages."

**Comment by magus-prime** [comment]
That would be helpful and appreciated.  Two things I would ask you to consider is that:

1. Especially on day one or two, when I've really needed MP restoration I would discover that the script had already consumed the daily limit of twenty-three sausages.

2. It's also a balancing act, early in a run, where meat is scarce and sausage creation takes meat that might be better conserved for other purposes.

The above become far less important in SC.
