### ISSUE TITLE
Can't start script today "You are currently in a fight."

### ISSUE THREAD

**Issue by faceboogle** [soolar/sl_ascend#151]
Yesterday the script got into trouble in a combat. I was leaving home and finished the day using the mobile client. Today it remembers being in a fight - even though it isn't any more - and won't start. Just says "You are currently in a fight."

I have tried:

- having a combat adventure manually

- being in a fight

- making changes to the settings and restarting it

- refreshing the session in mafia

Any suggestions?

**Comment by jaspercb** [comment]
That's... weird, and unfortunately not one of our error messages. I think that's a KoLmafia thing. In decreasing order of optimism:
1. `refresh all`
2. turn mafia on and off again
3. cry
4. clean install of mafia for today
5. set fire to computer, it has sinned

**Comment by faceboogle** [comment]
I don't know what I did but it seems to have started again.

Actually, what I did was run random scripts (which all failed):
> call scripts/sl_ascend/sl_util.ash
> call scripts/sl_ascend/sl_combat.ash
> call scripts/sl_ascend/sl_adventure.ash

Now running. Leaving this open I guess, but fine if you want to close it or want me to close it

**Comment by jaspercb** [comment]
Note that none of those scripts define `main()` or should be called like that.
I'd close, sounds like something weird happened but it's not clear what we can do to fix it.

**Comment by txrangersxx** [comment]
This is a mafia issue.  It still thinks you are in a fight and it won't do anything till you manually resolve

**Comment by faceboogle** [comment]
Thanks for the comments, closing this now.
