### ISSUE TITLE
Use spacegate vaccine when putting on jammies

### ISSUE THREAD

**Issue by taltamir** [soolar/sl_ascend#156]
When you run sl_ascend when overdrunk (or just full and out of adventures if vampyre) it prepares you for rollover. Putting on items that have +adv on rollover, etc.
At this time it should check to see if you still have your spacegate vaccine and if so use it. Otherwise it just goes to waste. (the vaccine gives a buff that does persist across rollover. only spending adventures uses up said buff)

**Comment by jaspercb** [comment]
Does KoLmafia know you have spacegate? `set spacegateAlways=true`

I ask only because, uh, it works for me ;)

**Comment by jaspercb** [comment]
nevermind, you're right, we only use spacegate for the Cyrpt +ML apparently. Hm.
