### ISSUE TITLE
Use macrometeorite + vote monsters to get lobsterfrogmen

### ISSUE THREAD

**Issue by soolar** [soolar/sl_ascend#16]
Sometimes it can't figure out getting +combat and so it just gives up on doing the LFM, meaning the war takes twice as long. This would also speed up LFM even if you can manage +combat because it's optimal.

**Comment by soolar** [comment]
Also portscan and maybe some other things.

**Comment by magus-prime** [comment]
But in a HC Sauceror run it gave up on doing The Lighthouse and blew many, many turns before it could attempt The Orchard.
