### ISSUE TITLE
Could we use Kramco goblins to burn delay?

### ISSUE THREAD

**Issue by jaspercb** [soolar/sl_ascend#160]
Ezandora's Guide script seems to have some hacked-together "you should expect a goblin next turn" logic. If we're equipping the sausage grinder every turn this isn't incredibly helpful, but if we're only equipping it when an internal timer is fairly high, we might be able to use this to burn delay? I'm not sure how this turn shaving would trade off against the turngen lost from fewer sausages.

**Comment by taltamir** [comment]
The first few goblins a day have a very high chance of appearing right away and in a row. So one thing that can be done is to start off the day prioritizing delay zones with a grinder

**Comment by Saklad5** [comment]
I recommend making a setting, default false, that leads to adventuring in delay zones when the chance _should_ be 100%. If that ends up not being the case, the script should abort with a message to report it.
