### ISSUE TITLE
mp auto recovery target is being set twice for vampyres

### ISSUE THREAD

**Issue by taltamir** [soolar/sl_ascend#162]
When you run the script it does:
```
hpAutoRecovery => -1
hpAutoRecoveryTarget => -1
**mpAutoRecovery => -1
mpAutoRecoveryTarget => -1**
manaBurningTrigger => -1
manaBurningThreshold => -1
**mpAutoRecovery => -0.05
mpAutoRecoveryTarget => 0.0**
```
I am pretty sure the second instance of setting mp recovery to off is because I am a vampyre, And is redundant.

**Comment by soolar** [comment]
Sure, it might be pointless, but it doesn't really seem worth taking effort to fix, since it's harmless.
