### ISSUE TITLE
Script reconfiguring skills on DG day 1 seems not working

### ISSUE THREAD

**Issue by xande-1** [soolar/sl_ascend#167]
So I start the script on day 1 of a DG run during the initial Torpor, right after the intro NC.  It buys skills, refreshes a bunch of stuff, and then gets its 7 blood bags for the day, and then I see this in the GCLI:

Session data refreshed.
choiceAdventure1003 => 0
CCS set to null
You acquire blood bag (7)
**You have learned Flesh Scent
You have forgotten Intimidating Aura
You have learned Macabre Cunning**
You acquire an item: letter from King Ralph XI
Using 1 letter from King Ralph XI...

However, notice that it's not in the Torpor NC at that point (no "Encounter: Torpor" line).  Interrupting the script and checking skills reveals that the changes printed in the CLI haven't happened.  i.e., my character still knows Intimidating Aura, and doesn't know Macabre Cunning or Flesh Scent.  Seems like a step of entering Torpor got missed somewhere.  :/

This **might** affect days other than day1, but that's the only place I've verified it happening (so far).

PS - Sorry for opening so many issues!  :(

**Comment by MatthewDarling** [comment]
I might have had the same experience in an earlier run. But now I have enough base HP to keep all skills, so I can't test this anymore :(

Can you try to reproduce the issue on your next run? If you have full logs for the start of a run where this happened, that would help too.

**Comment by jaspercb** [comment]
So the problem is that KoLmafia tracks skill changes even on a failed Torpor ( I think it checks the outgoing URL) Somehow we're submitting an invalid skill checklist, and this makes KoLmafia think our skills have changed even when they haven't. I tried to track down where the error is stemming from and couldn't. Logs would still be welcome, though.
