### ISSUE TITLE
Avatar of Sneaky Pete

### ISSUE THREAD

**Issue by Bisten** [soolar/sl_ascend#177]
The script just straight breaks when I try to run AoSP. There's a bad function in line 28.

**Comment by jaspercb** [comment]
Oh dear! Can you double-check you're running `sl_ascend.ash` and not `sl_sneakypete.ash`? If you're running `sl_ascend`, please post the full error log (presumably something to do with equipBaseline()) and I'll follow up.

**Comment by Bisten** [comment]
Is the other one defunct? I’ll go ahead and close, let me know if I should reopen

**Comment by Bisten** [comment]
I ran the normal script with AoSP for a couple days, but now the script is unequipping everything and can't make it through combat.

**Comment by Bisten** [comment]
I updated and it's all cool now.
