### ISSUE TITLE
Magical sausage casings being used when sl_saveMagicalSausage set to true

### ISSUE THREAD

**Issue by Stolio** [soolar/sl_ascend#18]
During an HCCS, sl_ascend generated 7 casings, then converted 3 of them into magical sausages and left the the remaining 4 as casings. sl_saveMagicalSausage is set to true.

**Comment by soolar** [comment]
It avoids eating the sausage, but does convert them as able. It tries to save 5k meat so you don't go broke. You're free to manually convert more casings to sausage if you want to be poor.
