### ISSUE TITLE
Doing haunted library twice

### ISSUE THREAD

**Issue by Bisten** [soolar/sl_ascend#186]
The script ran through the library even after the second floor was completed. It didn't do so after starting the third floor by talking to Lady Spookyraven.

**Comment by txrangersxx** [comment]
I may have been for the Copperhead quest

**Comment by Bisten** [comment]
No, the copperhead quest wasn’t unlocked and it specifically was seeking writing desks. After getting 5, it stopped and told me to give the necklace to Lady Spookyraven who was hanging out on the third floor.

**Comment by jaspercb** [comment]
Were you using Mafia, on one computer, for this entire ascension? I can see how you'd get into that state if you did the original library outside of Mafia, but I can't figure out how the script as-is would run the library twice if Mafia was tracking the original run through the library.

**Comment by Bisten** [comment]
The script ran both through both instances of the library on the same computer on mafia, though not at the same instances of Mafia. I suppose it’s possible that the data got lost between the two instances of running Mafia. It might be worth it to check if one of the upstairs locations is adventurable before adventuring in the library, but I’ll go ahead and clear this and chalk it up to something going wrong with my Mafia installation. I’ll let you know if I run into it again.

**Comment by jaspercb** [comment]
By "instance of Mafia" do you mean "I turned Mafia off and on again in between" or "Mafia was running from a different directory/installation". I'm worried about per-ascension tracking preferences (specifically, # of writing desks fought) being lost - and this wouldn't be lost if you closed and reopened Mafia, but would be lost if you ran Mafia from a different folder.

Hope this never shows up again! :)
