### ISSUE TITLE
Setting choiceAdventure values

### ISSUE THREAD

**Issue by magus-prime** [soolar/sl_ascend#189]
I tried sl_ascend on a Dark Gyffte run today and noticed that it wasn't taking advantage of the Death Rattlin' choiceAdventure.

```
Encounter: Death Rattlin'
Could not parse: You lose interest in the drawers and wander off
```
On checking the choiceAdventure value it was set to skip.  Is setting choiceAdventures outside the scope of the script?

**Comment by jaspercb** [comment]
That's not outside the scope of the script, we should be doing that. I thought we were doing that...

**Comment by magus-prime** [comment]
On Day Two I had to set the choiceAdventure value for Blech House.

**Comment by jaspercb** [comment]
Out of curiosity, what version of Mafia you're running? We currently only set the Blech House choice adventure when we *know* it's about to happen, and if your version of Mafia is old maybe it isn't tracking that?

**Comment by magus-prime** [comment]
Version 19193 when I hit the issue.
