### ISSUE TITLE
Still getting galoshes in HC Dark Gyffte

### ISSUE THREAD

**Issue by magus-prime** [soolar/sl_ascend#193]
This commit "[vampyre] Save blackberries for turns not galoshes" doesn't seem to have worked.  With the script as it is on the morning of 5/1/19 with r19197 of KoLmafia, the script spent blackberries on galoshes.

**Comment by jaspercb** [comment]
Oh no! I'll look into it.

**Comment by Saklad5** [comment]
https://github.com/soolar/sl_ascend/blob/53306cebe233159605da0cef6a32bedb8c3b8af5/RELEASE/scripts/sl_ascend.ash#L13174-L13178

That’s the culprit.
