### ISSUE TITLE
Stuck in death loop against wall of meat

### ISSUE THREAD

**Issue by michaeljhopkins** [soolar/sl_ascend#204]
I got stuck in a death loop against the wall of meat. One possible reason is that the ml was +30 something. The last battle in the linked pastebin is a manual "sauce geyser every attack"

https://pastebin.com/wcbwBfbx

**Comment by jaspercb** [comment]
The log doesn't show what class you were, which is pretty relevant for diving through the combat logic. Could you add that?

**Comment by michaeljhopkins** [comment]
Sorry about that. Accordion Theif
