### ISSUE TITLE
Castle in the Clouds in the Sky (Top Floor) NC not properly handled

### ISSUE THREAD

**Issue by magus-prime** [soolar/sl_ascend#209]
This occurred in a SC Std run and the character did have the mohawk wig in inventory:  while hunting for the Frattlesnake on the top floor of the castle, with the castle quest unfinished, the script hit the NC that would have ended the quest, twice, but was not wearing the mohawk wig.

That resulted in an unhandled choiceAdventure.

**Comment by taltamir** [comment]
The frattlesnake's current location is the smut orc logging camp.
http://kol.coldfront.net/thekolwiki/index.php/The_Frattlesnake

IIRC the script looks for it in the current location, it might have been hunting for something else from shen at the castle?

**Comment by magus-prime** [comment]
Sorry about that it was a "snake typo".  I just rechecked my session logs and the script was searching for the Burning Snake of Fire

**Comment by magus-prime** [comment]
It just happened again today.  Even after manually equipping the Mohawk wig after the script stopped.  When I restarted the script it equipped the beer helmet.

**Comment by magus-prime** [comment]
Today it failed while looking for The Snake With Like Ten Heads for the same reason.  Castle quest was unfinished and The Hole in the Sky was unopened.  The script insisted on wearing a Beer Helmet when a Mohawk wig was available.  I adventured manually to finish the quest and open the Hole in the Sky.

**Comment by taltamir** [comment]
I thought I saw a patch note a day or two ago saying this was supposedly fixed. If you saw it 17 hours ago then apparently not.

**Comment by magus-prime** [comment]
It was still happening with sl_ascend at 449.

**Comment by Saklad5** [comment]
I can confirm this is still occurring.

**Comment by taltamir** [comment]
interestingly enough, this just happened to me for the first time. It had
http://kol.coldfront.net/thekolwiki/index.php/Fuzzy_earmuffs
equipped instead of the mohawk wig
