### ISSUE TITLE
You can't equip a gelatinous cubeling with your current restrictions.

### ISSUE THREAD

**Issue by drthtater** [soolar/sl_ascend#213]
This script does NOT like Bees Hate You

I keep getting `You can't equip a gelatinous cubeling with your current restrictions.` and then the script just stops.

**Comment by jaspercb** [comment]
Oh, good catch - I'll add the "you don't have familiars with b's in their name in Bees Hate You" check and the rest... *should* sort itself out.

Although I suspect Bees Hate You still won't work. Yikes.
