### ISSUE TITLE
Turn down +ML  after getting to Level 13

### ISSUE THREAD

**Issue by txrangersxx** [soolar/sl_ascend#231]
Script needs to lower ML after getting to Level 13 so you are assured to get the instant karma

**Comment by jaspercb** [comment]
I think we already do this, a bit. Is there a specific +ML buff that you're noticed being used?

**Comment by taltamir** [comment]
I think this should be a setting. I personally would prefer it didn't tune down the level grinding once reaching 13 as it saves me some turns in aftercore of level grinding

**Comment by txrangersxx** [comment]
Im at +50 because of some of my equipment

**Comment by jaspercb** [comment]
Which equipment?

**Comment by txrangersxx** [comment]
Sorry I have to wait till I get back to that level doing 2 day ascensions.  The equipment causing is the barrell lid

**Comment by Saklad5** [comment]
I think there should be a setting for controlling when to tone down ML. By default, it should stop when you are _at_ level 13, but ramp it right back up if you go beyond that. Right now it stops if you are at _or above_ 13, which doesn’t really make sense.

**Comment by taltamir** [comment]
> I think there should be a setting for controlling when to tone down ML. By default, it should stop when you are _at_ level 13, but ramp it right back up if you go beyond that. Right now it stops if you are at _or above_ 13, which doesn’t really make sense.

This is an excellent point, if you are already level 14 there is no point in not ramping it back up

**Comment by Phate4569** [comment]
In TCRS I had this issue yesterday with Kramco adding +10 ML (I'd walked away for 80 Battlefield fights so I didn't notice).

I had to hide it in my closet to keep the script from equipping the item.

**Comment by faceboogle** [comment]
Specifically I have noticed the script using Pride of the Puffin, Drescher's (sp?) Annoying Noise. And spending free turns at the Never-ending Party. 
It was pretty determined that I shouldn't get the Instant Karma :)
