### ISSUE TITLE
Use Cat Burglar heists for free runs and such

### ISSUE THREAD

**Issue by Saklad5** [soolar/sl_ascend#233]
The following items are probably worth heisting in many cases:

- Cigarette lighter (to speed up A Mob of Zeppelin Protesters)
- Rusty hedge trimmers (to speed up Twin Peak)
- Short writ of habeas corpus (to speed up Hidden City)

These are all nearly guaranteed to save turns. It may not be worth switching to the Cat Burglar just to use it for these, but if you happen to have the opportunity they are valuable targets.

**Comment by jaspercb** [comment]
I can see the reasoning for the cigarette lighter and rusty hedge trimmers, but spending a heist to save 1 adventure (short writ) doesn't seem worth it. Might be wrong on this.

My other concern with pickpocketing rusty hedge trimmers is that we could easily burn a *ton* of pickpockets on it and not have any left for mitigating bad RNG for the Airship or other quests. But I agree it's helpful and would save some turns, and in a 3-day run we don't get anywhere close to using all 6 pickpockets, so I'll have to think about that.

**Comment by Saklad5** [comment]
> My other concern with pickpocketing rusty hedge trimmers is that we could easily burn a _ton_ of pickpockets on it and not have any left for mitigating bad RNG for the Airship or other quests. But I agree it's helpful and would save some turns, and in a 3-day run we don't get anywhere close to using all 6 pickpockets, so I'll have to think about that.

By the time sl_ascend gets to these items in my runs, there aren’t any designated heist targets remaining. It could be coded to only use heists on them if it is sure the more useful options have passed, potentially.
