### ISSUE TITLE
Does not utilize ML +11 in Little Canada

### ISSUE THREAD

**Issue by Phate4569** [soolar/sl_ascend#243]
Noticing that the script does not utilize ML+11 in Little Canada, even when complaining that it can not get enough ML for Rock Fliers.

**Comment by Saklad5** [comment]
That’s really weird, since the code definitely has some sort of coverage for that already:
https://github.com/soolar/sl_ascend/blob/aa4435c661836dd2c35bae0e409f0240fe138aab/RELEASE/scripts/sl_ascend/sl_util.ash#L2942-L2945

**Comment by Phate4569** [comment]
The last 2 ascentions seem to have worked. The only differences were that I updated mafia, presumably updated this script (it auto updates) and went into HC instead of softcore.
