### ISSUE TITLE
drunken stupor

### ISSUE THREAD

**Issue by taltamir** [soolar/sl_ascend#245]
It is possible for sl_ascend to waste a turn on drunken stupor.

1. Drink to 20/20 and run sl_ascend until done. (1 adv left)
2. Switch familiar to stooper
3. Drink a size 1 drink to be at 21/21 drunkness
4. run sl_ascend (I meant to overdrink but forgot)

At this point sl_ascend will switch out from stooper to another familiar, changing drunkness to 21/20, and then attempt to adventure someone and get a drunken stupor adventure. Only 1 and then it does the prep for overnight, but that is still 1 wasted adventure.

There needs to be an additional check after changing familiar but before doing the adventure.

**Comment by jaspercb** [comment]
that's hilarious, thanks for the find
