### ISSUE TITLE
Don't go get missing White Pixels in OCRS till right before going into the sorceress lair

### ISSUE THREAD

**Issue by txrangersxx** [soolar/sl_ascend#247]
I would like to see the script not get white pixels in OCRS till the very last minute so you don't waste turns in fear mans level if you are very close to having enough

**Comment by jaspercb** [comment]
This seems really marginal. I don't think it's worth the effort to fix, sorry. Eking a few turns out of a path that we already barely support doesn't seem worth complicating quest scheduling.
