### ISSUE TITLE
Various HC issues

### ISSUE THREAD

**Issue by Phate4569** [soolar/sl_ascend#248]
Running 2CRS and these last 2 runs have been HC, I've encountered the following issues:

- Stops doing Trapper Quest after milk. Does not attempt to get Mining Gear, nor will it mine once the gear is aquired.
- Uses eXtreme slope to get to peak, but forgets to put on eXtreme gear and gets stuck in a loop trying to get to the peak.
- Aforementioned attempting to powerlevel to remedy missing pool skill.
- Can not open Hidden City (2CRS), must be manually taken over.

Annoyances:
- Uses daycare but doesn't prompt or allow user to add toddlers.
- Never selects to help at Neverending party. IMO it is better for the meta if the script tries to help if Drinking To drink isn't yet acquired. (Maybe user setable? If selected it completes the party quest daily?)
- Doesn't seem to want to use pocket wishes even with allow wishes setting enabled.

**Comment by Phate4569** [comment]
> Uses eXtreme slope to get to peak, but forgets to put on eXtreme gear and gets stuck in a loop trying to get to the peak.

Updated again today and it did not do this.

> Doesn't seem to want to use pocket wishes even with allow wishes setting enabled.

After update today it successfully used 2 pocket wishes!

**Comment by jaspercb** [comment]
Ore in HC is currently only auto-acquired if you have the Cat Burglar and the Genie Bottle - it'll wish for a Mountain Man and then heist it.

I'm... confused why you'd want toddlers added to the daycare in-run. Maybe I'm missing something - is there a specific optimization you have in mind? In any case, I don't think we should prompt over something as minor as daycare usage.

I figured out what's going on with the Hidden City failed unlocks (in 2CRS specifically) and will patch later today.

**Comment by Phate4569** [comment]
> Ore in HC is currently only auto-acquired if you have the Cat Burglar and the Genie Bottle - it'll wish for a Mountain Man and then heist it.

Ah, ok, so it doesn't mine for them. :/

>I'm... confused why you'd want toddlers added to the daycare in-run. Maybe I'm missing something - is there a specific optimization you have in mind?

PvP, and getting bouquets for 2CRS.

**Comment by Phate4569** [comment]
> Ore in HC is currently only auto-acquired if you have the Cat Burglar and the Genie Bottle - it'll wish for a Mountain Man and then heist it.

Bought Kitten burgler and have 2 wishes remaining, this still does not seem to work in HC 2CRS.

**Comment by Phate4569** [comment]
>I figured out what's going on with the Hidden City failed unlocks (in 2CRS specifically) and will patch later today.

Still doesn't do it intelligently. The mafia data files contain a whole list of sources of Stone-Faced. For example, I am in SC/Opossum and can just buy goofballs, should take 4 adv or so.

https://www.reddit.com/r/kol/comments/c4q1tr/2crs_stonefaced_sources/
