### ISSUE TITLE
Try not to kill gremlins prematurely

### ISSUE THREAD

**Issue by zweq** [soolar/sl_ascend#261]
In L12_gremlins(), familiar is chosen with handleFamiliar("init"). It chooses the first applicable out of Happy Medium, Xiblaxian Holo-Companion, Oily Woim and Cute Meteor. Since I didn't have any of the first three (yup, I seem to have missed getting an Oily Woim), it ended up going against the gremlins with Cute Meteor, equipped with a tiny bowler as the cherry on top. Gremlins had a hard time revealing their tools before being exterminated.

**Comment by soolar** [comment]
Oh dear. I've added a new gremlins category for familiars, which looks solely at non-blocking, non-damaging delevelers (worst case being barrrnacle, best case being nosy nose). You'll have to enable sl_beta_test to benefit from this, for now.
