### ISSUE TITLE
Auto Collect Pirate Realm Eyepatch

### ISSUE THREAD

**Issue by Phate4569** [soolar/sl_ascend#264]
In 2CRS the eyepatch can have some pretty great abilities. I suggest pulling it during the breakfast portion of the script if we don't have it already.

File attached with the dump of effects.

[PiratePatch.txt](https://github.com/soolar/sl_ascend/files/3346637/PiratePatch.txt)

**Comment by jaspercb** [comment]
We already do this.

**Comment by Phate4569** [comment]
Ah. ok. It isn't in the relay portion. I set that up for NEP and Fantasy, I figured it didn't exist because the option is missing.
