### ISSUE TITLE
Consider olfacting blue oyster cultists in the Mob of Zeppelin Protesters

### ISSUE THREAD

**Issue by magus-prime** [soolar/sl_ascend#27]
Olfacting blue oyster cultists, getting the lighter drop, and using the lighters in combat would help in reducing the number of turns spent in the zone.  The script will use the lighter if it has one but olfacting the cultists would help.

**Comment by Malibu-Stacey** [comment]
I've added this for Ed in PR #215 (and actually throwing the cigarette lighters at protestors) but other paths could likely benefit from similar changes.

**Comment by Malibu-Stacey** [comment]
Fixed on 59944de on 11th May by soolar.
