### ISSUE TITLE
Please save and restore old outfit when eating sausage

### ISSUE THREAD

**Issue by crowkol** [soolar/sl_ascend#29]
In "sl_ascend/sl_mr2019.ash" on or about line 98, this is done, "maximize("mp,-tie", false);", which is awesome.   However, when that has finished, the code continues to adventure while wearing a max MP outfit instead of what it was wearing before.  It would be better to save and restore the old outfit.

**Comment by soolar** [comment]
Oops, good call, thanks for the report!

**Comment by soolar** [comment]
ee5b38480eff57f9034634a63c959225f7a6d06e
