### ISSUE TITLE
Maximizer issue since latest Mafia Update

### ISSUE THREAD

**Issue by Phate4569** [soolar/sl_ascend#291]
`Script execution aborted (java.lang.NullPointerException): (sl_util.ash, line 182)`

Running Mafia XX47, script not updated since I am still running my test version. I inserted debug lines.

It is failing in `void L9_chasmMaximizeForNoncombat()` on the line `simMaximizeWith(moxtry);`

I traced it down to `sl_util` in `slMaximize()`, the line `return maximize(req, simulate);`

![MaximizeFailureDrilldown](https://user-images.githubusercontent.com/51530157/61996389-d0a06680-b061-11e9-995b-3c4bc9669ac5.png)
![MaximizerFailure](https://user-images.githubusercontent.com/51530157/61996390-d0a06680-b061-11e9-9bb4-ef7e48057a2b.png)

**Comment by Phate4569** [comment]
From what I can tell this was introduced somewhere between 19443 and 19447

**Comment by jaspercb** [comment]
I believe this is a Mafia issue - r19445 changed the maximizer to support beach heads, one of which gives +Moxie.

**Comment by jaspercb** [comment]
Fixed upstream in r19448.
