### ISSUE TITLE
pre or post adventure script removes unstable fulminate

### ISSUE THREAD

**Issue by Muczachan** [soolar/sl_ascend#301]
The script just terminated after spending more turns than the cutoff in the Boiler Room. So I tried to get the fulminate heated manually... Alas I had to turn off the pre and post scripts to be able to do so:
equip off-hand unstable fulminate
> Starting preadventure script...
> Maximizing: 5item,meat,0.5initiative,0.1da 1000max,dr,0.5all res,1.5mainstat,mox,-fumble,0.4hp,0.2mp 1000max,6mp regen,0.25spell damage,1.75spell damage percent,-equip hewn moon-rune spoon,-equip makeshift garbage shirt,-equip broken champagne bottle,-equip Snow Suit,+equip latte lovers member's mug

equip hat wad of used tape

equip weapon Fourth of May Cosplay Saber

equip off-hand latte lovers member's mug

equip pants bloodied surgical dungarees
> Pre Adventure at The Haunted Boiler Room done, beep.

equip off-hand unstable fulminate
> Starting preadventure script...
> Maximizing: 5item,meat,0.5initiative,0.1da 1000max,dr,0.5all res,1.5mainstat,mox,-fumble,0.4hp,0.2mp 1000max,6mp regen,0.25spell damage,1.75spell damage percent,-equip hewn moon-rune spoon,-equip makeshift garbage shirt,-equip broken champagne bottle,-equip Snow Suit,+equip latte lovers member's mug,+equip latte lovers member's mug

equip off-hand latte lovers member's mug
> Pre Adventure at The Haunted Boiler Room done, beep.

equip off-hand unstable fulminate
> Starting preadventure script...
> Maximizing: 5item,meat,0.5initiative,0.1da 1000max,dr,0.5all res,1.5mainstat,mox,-fumble,0.4hp,0.2mp 1000max,6mp regen,0.25spell damage,1.75spell damage percent,-equip hewn moon-rune spoon,-equip makeshift garbage shirt,-equip broken champagne bottle,-equip Snow Suit,+equip latte lovers member's mug,+equip latte lovers member's mug,+equip latte lovers member's mug

equip off-hand latte lovers member's mug
> Pre Adventure at The Haunted Boiler Room done, beep.

equip off-hand unstable fulminate

[623] The Haunted Boiler Room
Encounter: steam elemental
Round 0: muczachan wins initiative!
Round 1: muczachan attacks!
Round 2: muczachan wins the fight!
You acquire an item: CSA scoutmaster's &quot;water&quot;
You acquire an item: Ka coin
After Battle: You gain 15 Strongness
After Battle: You gain 43 Enchantedness
After Battle: You gain 11 Cheek

**Comment by Phate4569** [comment]
Looks to be the same issue as #276 and #271 most likely related to latte being able to Banish.
