### ISSUE TITLE
sl_ascend wants to buy expensive IOTM

### ISSUE THREAD

**Issue by taltamir** [soolar/sl_ascend#308]
I tried to run sl_ascend in bees hate you path and CLI said:

> Searching for "Pantsgiving"...
> Search complete.
> Do not have enough meat in Hagnk's to buy Pantsgiving. Need 240000000 have 230508002.
> You must be a poor meatbag.
> Searching for "filthy child leash"...
> Search complete.
> Using cached search results for filthy child leash...
> Purchasing filthy child leash (1 @ 150)...
> Purchases complete.

when it was buying and pulling things. that really shouldn't be doing this. Luckily i was short 10 million meat and so it couldn't afford to buy pantsgiving for 240 million

**Comment by jaspercb** [comment]
there's a `pullXWhenHaveY($item[Pantsgiving], 1, 0);` lying around, which tries to mallbuy the item. Huh, good find. I couldn't find any code changes that would have introduced this behavior, which surprises me.

**Comment by jaspercb** [comment]
In industry I would rename `pullXWhenHaveY()` to something like `pullXWhenHaveY_UNSAFE_MALLBUY()` to avoid future footguns of this sort. Might be worth doing.

**Comment by jaspercb** [comment]
Oh, it doesn't actually buy the item even if you have enough meat. The log is misleading, will fix.

**Comment by taltamir** [comment]
Oh, interesting. well its good that it doesn't buy it even if you have the meat.
