### ISSUE TITLE
don't release the boots against eldritch tentacle

### ISSUE THREAD

**Issue by taltamir** [soolar/sl_ascend#313]
sl_ascend tried to use release the boots against eldritch tentacle, which is a waste of a stomp, and also caused it to get stuck

> Visiting a Science Tent
> Encounter: Dr. Gordon Stuart, a Scientist
> 
> [186] Dr. Gordon Stuart's Science Tent
> Encounter: Eldritch Tentacle
> Round 0: taltamir wins initiative!
> Round 1: Bubediah rubs its soles together, then stomps in place restlessly. Clearly, the violence it's done so far is only making it ache for some quality stomping. (Use the "Release the Boots" skill to let it go nuts.)
> slAdvBypass has encountered a combat! (param: 'sl_combatHandler')
> nextAdventure => Noob Cave
> 
> [186] Noob Cave
> Encounter: Eldritch Tentacle
> Round 0: taltamir loses initiative!
> sl_combatHandler: 0
> Round 1: taltamir casts RELEASE THE BOOTS!
> Round 2: Bubediah shuffles its heels, gets a running start, then leaps on it and stomps mightily for 52 damage.
> Round 2: Eldritch Tentacle takes 52 damage.
> Round 2: You lose 19 hit points
> You're on your own, partner.
> Click here to continue in the relay browser.

**Comment by jaspercb** [comment]
simple fix, will add Eldritch Tentacle to `is_instakillable()`
