### ISSUE TITLE
tower init test, actually stop when you have enough to reach 2nd place

### ISSUE THREAD

**Issue by taltamir** [soolar/sl_ascend#329]
when preparing for the tower init test on 2crs, it went well over 2000 initiative, wasting (admittedly cheap) +init items well after it had reached the needed init to get to 2nd place

Before using each item, it should test if init is high enough, and if yes sign up instead of buffing it further

**Comment by Saklad5** [comment]
I recently saw it maximize for the tower tests, then undo all of that when maximizing during pre-adventure operations. I haven’t replicated this without beta being enabled, so take that with a grain of salt.

**Comment by jaspercb** [comment]
I currently think that happens for the initiative test but not for others, and have a fix pending. If you see it happening on other tests, please let me know!

**Comment by jaspercb** [comment]
The fix is "remove the call to `presool`, why was that there in the first place?"

**Comment by Saklad5** [comment]
> The fix is "remove the call to `presool`, why was that there in the first place?"

When was it added?

**Comment by jaspercb** [comment]
> When was it added? What's the point of version control if we have to guess?

Looks like it was last touched in e8f955341, seven months ago - and that was one of the big "batch rename everything" commits. I think it's safe to remove.

**Comment by Saklad5** [comment]
> Looks like it was last touched in [e8f9553](https://github.com/soolar/sl_ascend/commit/e8f955341154eb9ffdc80e3c84b1ec28afd12b4e), seven months ago - and that was one of the big "batch rename everything" commits. I think it's safe to remove.

When was the call added, name aside? I admit I'm not that familiar with GitHub's blame interface.

**Comment by Saklad5** [comment]
Unfortunately, it looks like that change _wasn't_ under version control, at least in the context of this repository. The call to `precheese` was in the initial commit.

**Comment by Saklad5** [comment]
On a related note, I really wish ASH had a more sophisticated scope system. Everyone ends up using `cli_execute` instead of `import` due to unavoidable namespace collisions, or embedding all the functions in `main` to sidestep the same. Scripts would be much easier to read if you could make functions `private`.

**Comment by jaspercb** [comment]
> I can only assume there was a reason for it at some point, even if there doesn't appear to be one now.

Original commit was in January 2016, at https://sourceforge.net/p/ccascend/code/637/

I think it's safe to remove now.
