### ISSUE TITLE
Set MCD to ML +11 when Ascending under a Canadia Moon Sign

### ISSUE THREAD

**Issue by RobuxShooters** [soolar/sl_ascend#37]
Because of the removal of the pirates' route for ascending, I've been taking the Marmot moon sign when ascending to get the ten-leaf clovers to help in various quests in my adventure. I've been noticing that the script does not want to set the MCD to 11 when ascending under a Canadia moon sign, instead preferring to set it at 10. Perhaps this is an unintended result from last years' ascension, where most players prefer the Degrassi Knoll moon sign.

**Comment by Rinn** [comment]
Fixed with https://github.com/soolar/sl_ascend/commit/78042191cf04d95131e9d2377ca05c2635b1425d

**Comment by Saklad5** [comment]
Consider closing this issue.
