### ISSUE TITLE
Trying to get steel organ in Dark Gyffe

### ISSUE THREAD

**Issue by txrangersxx** [soolar/sl_ascend#59]
Script is trying to get the steel organ in Dark Gyffe, and in Dark Gyffe you cant use the steel organ

**Comment by jaspercb** [comment]
This is controlled by a setting that's set in DG runs at https://github.com/soolar/sl_ascend/blob/master/RELEASE/scripts/sl_ascend/sl_batpath.ash#L16. Is it possible your run was adventuring in Pandemonium to try to obtain hot wings?

**Comment by txrangersxx** [comment]
Why would need hot wings in DG?  They are not used for food, and you don't need to do pirates.  So it shouldn't be trying for hot wings

**Comment by txrangersxx** [comment]
It only did 5 turns then went and did the crypt.  Don't know why it would even need to go to the slums

**Comment by jaspercb** [comment]
fixed
