### ISSUE TITLE
Allow use of own custom combat script 

### ISSUE THREAD

**Issue by txrangersxx** [soolar/sl_ascend#60]
Allow the use of your own custom combat script instead of the default combat script from the script

**Comment by jaspercb** [comment]
I think this would break a lot of the tricks that sl_ascend attempts and so I don't support it. *You are free to fork and change or replace sl_ascend's combat script,* but I don't want to have to support a dozen different combat scripts with subtle interactions and assumptions about which skills are available and when it's OK to flyer.

**Comment by Saklad5** [comment]
This issue should probably be closed.

**Comment by txrangersxx** [comment]
Closing
