### ISSUE TITLE
Strongly consider replacing ccs with a consult script

### ISSUE THREAD

**Issue by soolar** [soolar/sl_ascend#8]
The ccs is kind of a nightmare and things like banisher handling could be massively improved by using a consult script instead. This'll be a lot of work, but I already have a consult script I use that could potentially be adapted to the role... Not happening until after equipment handling rewrite though.

**Comment by magus-prime** [comment]
Or allow the user to specify a CCS or consult script.  I user zarqon's SimpleSmack and it can, economically, handle 98% of all combats.

**Comment by soolar** [comment]
cc_ascend already had a consult script in place, it's just not called by a ccs. I'll open a separate task for improvements to the consult script
