### ISSUE TITLE
gingerbread mob hit

### ISSUE THREAD

**Issue by taltamir** [soolar/sl_ascend#87]
script currently uses various daily free kills such as shattering punch (skill that free kills 3 non boss enemies a day without spending a turn). The same mechanism should be extended to also apply to the gingerbread mob hit which free kills 1 enemy a day.

http://kol.coldfront.net/thekolwiki/index.php/Gingerbread_Mob_Hit

**Comment by jaspercb** [comment]
There's already code for that! I suspect the reason it's not using it when you expect it to be used is that the relevant code seems to only be willing to use free fights with less than 20 adventures left, in aftercore, or on day 3 or later. If you never run into a free fight with 20 adventures or less, it'll never use the free combat, which seems incorrect. I don't really know why this is there, and am asking around on the Discord.

```
if(canUse($skill[Chest X-Ray]) && equipped_amount($item[Lil' Doctor&trade; bag]) > 0 && (get_property("_chestXRayUsed").to_int() < 3))
{
	if((my_adventures() < 20) || get_property("kingLiberated").to_boolean() || (my_daycount() >= 3))
	{
		handleTracker(enemy, $skill[Chest X-Ray], "sl_instakill");
		return useSkill($skill[Chest X-Ray]);
	}
}
if(canUse($skill[shattering punch]) && (get_property("_shatteringPunchUsed").to_int() < 3))
{
	if((my_adventures() < 20) || get_property("kingLiberated").to_boolean() || (my_daycount() >= 3))
	{
		handleTracker(enemy, $skill[shattering punch], "sl_instakill");
		return useSkill($skill[shattering punch]);
	}
}
if(canUse($skill[Gingerbread Mob Hit]) && !get_property("_gingerbreadMobHitUsed").to_boolean())
{
	if((my_adventures() < 20) || get_property("kingLiberated").to_boolean() || (my_daycount() >= 3))
	{
		handleTracker(enemy, $skill[Gingerbread Mob Hit], "sl_instakill");
		return useSkill($skill[Gingerbread Mob Hit]);
	}
}
```

**Comment by taltamir** [comment]
That is some odd exclusion logic there. It looks like it is trying to save the free kills for aftercore? Honestly as far as I am concerned that exclusion logic can just go away.
`if(canUse($skill[Chest X-Ray]) && equipped_amount($item[Lil' Doctor&trade; bag]) > 0 && (get_property("_chestXRayUsed").to_int() < 3))
{
	handleTracker(enemy, $skill[Chest X-Ray], "sl_instakill");
	return useSkill($skill[Chest X-Ray]);
}
if(canUse($skill[shattering punch]) && (get_property("_shatteringPunchUsed").to_int() < 3))
{
	handleTracker(enemy, $skill[shattering punch], "sl_instakill");
	return useSkill($skill[shattering punch]);
}
if(canUse($skill[Gingerbread Mob Hit]) && !get_property("_gingerbreadMobHitUsed").to_boolean())
{
	handleTracker(enemy, $skill[Gingerbread Mob Hit], "sl_instakill");
	return useSkill($skill[Gingerbread Mob Hit]);
}`

Anyways, I suspect there is something off about gingerbread mob hit specifically since sl_ascend used shattering punch but not gingerbread mob hit on day 2 for me. Maybe this snippet
`!get_property("_gingerbreadMobHitUsed").to_boolean()`
is not working properly?

**Comment by taltamir** [comment]
derp. i figured out why it didn't work. gingerbread mob hit is out of standard now and is not available in standard. can close down this bug report
